config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  # post 'spots#create'
  get 'seasons/spring'
  get 'seasons/summer'
  get 'seasons/autumn'
  get 'seasons/winter'
  root 'spots#top'
  get '/', to: 'spots#top'
  # get '/spots/new', to: 'spots#new'
  # post '/spots', to: 'spots#create'
  resources :users,except:[:edit,:new,:create] do
    resource :relations,only:[:create,:destroy]
    get :follows, on: :member
    get :followers, on: :member
  end
  resources :relationships,only: [:create, :destroy]
  resources :spots,except:[:new] do
      resources :comments,only:[:create,:destroy,:edit,:update]
      resource :favorites,only:[:create,:destroy]
      resources :went_spots,only:[:create,:destroy]
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/spot.rb
class Spot < ApplicationRecord
	has_many :favorites,dependent: :destroy
	has_many :comments,dependent: :destroy
	has_many :went_spots,dependent: :destroy
    # carrierWaveを使う為の記述
	mount_uploader :images, ImagesUploader
    validates :spot_name,presence: true,length: {maximum:20}
    validates :description,presence: true,length: {minimum:10,maximum:210}
    validates :season,:prefecture,:spot_address,:images,presence: true
    # geocorderでアドレスから緯度経度を取得する為の記述
    geocoded_by :spot_address
    after_validation :geocode

        # DBには数値が保存されていて、表示される時だけ対応した文字列になる。
    	enum season: {
        '春':1,
        '夏':2,
        '秋':3,
        '冬':4,
    }
    	enum prefecture: {
        '東京':1,
        '神奈川':2,
        '埼玉':3,
        '千葉':4,
        '群馬':5,
        '栃木':6,
        '茨城':7,
    }
    def favorited_by?(user)
        favorites.where(user_id: user.id).exists?
    end
end

app/controllers/spots_controller.rb
class SpotsController < ApplicationController
  def top
    @spots = Spot.all
    @spot1 = Spot.find(3)
    @spot2 = Spot.find(4)
  end

  def show
    @spot = Spot.find(params[:id])
    @comment = Comment.new
    @comments = @spot.comments.all.order(created_at: :desc)
  end

  def edit
    @spot = Spot.find(params[:id])
  end

  def create
    @search = Spot.ransack(params[:q])
    @search_user = User.ransack(params[:q])
    @spots = @search.result.page(params[:spot_page]).per(6)
    @users = @search_user.result.page(params[:user_page]).per(8)
    @spot = Spot.new(spot_params)

    if @spot.save
      flash[:success] = "スポットを追加しました。"
      redirect_to users_path
    else
      flash[:alert] = "スポットの追加に失敗しました。"
      render "users/index"
    end
  end

  def update
    @spot = Spot.find(params[:id])
    @spots = Spot.page(params[:spot_page]).per(6)
    @users = User.page(params[:user_page]).per(8)
    if @spot.update(spot_params)
      flash[:success] = "スポットを編集しました。"
      redirect_to users_path
    else
      flash[:alert] = "スポットの編集に失敗しました。"
      render "users/index"
    end
  end

  def destroy
    spot = Spot.find(params[:id])
    spot.destroy
    redirect_to users_path
  end

  private
    def spot_params
      params.require(:spot).permit(:images, :spot_name, :description, :season, :prefecture, :spot_address, :latitude, :longitude, :average_star)
    end
end

app/helpers/spots_helper.rb
module SpotsHelper
end

app/views/spots/_edit.html.erb
<button type="button" data-toggle="modal" data-backdrop="true" data-target="#modal<%=spot.id%>-option" class="btn btn-default btn-sm user_edit">編集</button>

<div class="modal fade" id="modal<%=spot.id%>-option" tabindex="-1" role="dialog" aria-labelledby="myModalOptionLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h3 class="modal-title" id="myModalOptionLabel">スポット編集</h3>
        <button type="button" class="close" data-dismiss="modal" aria-label="閉じる"><span aria-hidden="true">&times;</span></button>
      </div>
      <div class="modal-body">
      		<%= form_for (spot) do |f| %>
		<div class="form-group">
			<%= f.label :spot_name, "スポット名", class:"label-bold" %><br>
			<%= f.text_field :spot_name,autocomplete: "spot_name" ,class:"form-ucr"%><br>
		</div>
		<div class="season_prefecture">
			<div class="form_season form-group">
				<%= f.label :season, "季節", class:"label-bold" %><br>
			    <%= f.select :season, Spot.seasons.keys, { prompt: '選択してください' } %>
			</div>
			<div class="form-group">
				<%= f.label :prefecture, "地域", class:"label-bold" %><br>
				<%= f.select :prefecture, Spot.prefectures.keys, { prompt: '選択してください' } %>
			</div>
		</div>
			<div class="form_address form-group">
				<%= f.label :spot_address, "場所", class:"label-bold" %><br>
				<%= f.text_field :spot_address ,class:"form-control form-ucr"%>
			</div>
		<div class="form-group">
			<%= f.label :description, "内容", class:"label-bold" %><br>
			<%= f.text_area :description ,class:"form-control form-ucr" %>
		</div>
		<div class="form-group">
			<%= f.label :images, "画像", class:"label-bold" %><br>
			<%= f.file_field :images, multipart: true %>
		</div>
		<div class="form-group">
			<%= f.submit '保存' ,class: "form-control btn btn-primary"%>
		</div>

	<% end %>

      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">閉じる</button>
      </div>
    </div>
  </div>
</div>

app/views/spots/_edit_comment.html.erb
<button type="button" data-toggle="modal" data-backdrop="true" data-target="#modal<%=comment.id %>-option" class="btn btn-default btn-sm user_edit">編集</button>

<div class="modal fade" id="modal<%=comment.id %>-option" tabindex="-1" role="dialog" aria-labelledby="myModalOptionLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h3 class="modal-title" id="myModalOptionLabel">コメントの編集</h3>
        <button type="button" class="close" data-dismiss="modal" aria-label="閉じる"><span aria-hidden="true">&times;</span></button>
      </div>
      <div class="modal-body">
        <div class="comment_post">
          <%#= form_for [@spot,comment] do |comment| %>
          <%= form_for [@spot,comment] do |comment| %>
            <%= comment.hidden_field :spot_id, value: @spot.id %>
            <div class="field" id="star">
                <%= comment.label :評価 %>
                <%= comment.hidden_field :star, id: :review_star %>
                ※５段階で評価をつけてください。
            </div>
            <%= comment.file_field :comment_image %>
            <label><%= comment.label :comment %></label><br>
            <%= comment.text_area :comment, :size => "50x5" %><br>
            <%= comment.submit "レビューを編集する", :class => "btn btn-primary form-control" %>
          <% end %>
          <script>
          $('#star').raty({
            size:36,
            starOff:  '<%= asset_path('star-off.png') %>',
            starOn : '<%= asset_path('star-on.png') %>',
            scoreName: 'comment[star]'
          });
          </script>
        </div>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">閉じる</button>
      </div>
    </div>
  </div>
</div>
<!-- 評価された星を表示する記述 -->
<script>
  $('.rated').raty({
    path: '/images/',
    readOnly: true,
    score: function() {
      return $(this).attr('data-score');
    }
  });
</script>

app/views/spots/_footer.html.erb
<div class="footer">
	<div class="footer_line">
	</div>
	<div class="footer_content">
		<p>©shikitabi.xyz</p>
	</div>
</div>

app/views/spots/_googlemap.html.erb
<button type="button" data-toggle="modal" data-backdrop="true" data-target="#modal999-option" class="btn btn-default">地図を表示する</button>

<div class="modal fade" id="modal999-option" tabindex="-1" role="dialog" aria-labelledby="myModalOptionLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="myModalOptionLabel">
          <%= @spot.spot_name %><br>
          <%= @spot.spot_address %>
        </h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="閉じる"><span aria-hidden="true">&times;</span></button>
      </div>
      <div class="modal-body">
    		<div class="maps">
    		  <iframe src="https://maps.google.co.jp/maps?output=embed&q=<%= @spot.spot_address%>" class="googlemap"></iframe>
    		</div>
    	</div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">閉じる</button>
      </div>
    </div>
  </div>
</div>

app/views/spots/_header.html.erb
<div class="header_container clearfix">
	<div class ="header_logo">
    <%= link_to root_path, target: "_blank" do %>
        <%= image_tag '/images/header_logo2.jpg'%>
    <% end %>
	</div>
  <!-- ハンバーガーメニューの内部 -->
  <div id="sp-menu">
      <h3 class="menu_title">メニュー</h3>
        <% if user_signed_in?%>
          <ul>
            <li><%= link_to "春",seasons_spring_path %></li>
            <li><%= link_to "夏",seasons_summer_path %></li>
            <li><%= link_to "秋",seasons_autumn_path %></li>
            <li><%= link_to "冬",seasons_winter_path %></li>
            <li><%= link_to "マイページ",user_path(current_user) %></li>
            <% if user_signed_in? && current_user.admin %>
              <li><%= link_to "管理者ページ",users_path%></li>
            <% end %>
            <li><%= link_to "ログアウト",destroy_user_session_path,method: :delete %></li>
            <li><%= link_to "トップページ",root_path %></li>
          </ul>
          <% else %>
          <ul>
            <li><%= link_to "春",seasons_spring_path %></li>
            <li><%= link_to "夏",seasons_summer_path %></li>
            <li><%= link_to "秋",seasons_autumn_path %></li>
            <li><%= link_to "冬",seasons_winter_path %></li>
            <li><%= link_to "ログイン",new_user_session_path%></li>
            <li><%= link_to "会員登録",new_user_registration_path%></li>
            <li><%= link_to "トップページ",root_path %></li>
          </ul>
        <% end %>
  </div>
  <div id="hm-icon">
      <a class="menu-trigger" href="#">
        <span></span>
        <span></span>
        <span></span>
      </a>
  </div>
</div>
<!--
    <script type="text/javascript" src="js/jquery.js"></script>
    <script type="text/javascript" src="js/script.js"></script>
 -->

app/views/spots/_index.html.erb
<div class="admin_spot_table">
	<!-- テーブルのタイトル部分 -->
	<div class="admin_spot_item_title">
		<div class="spot_image_btn">スポット
		</div>
		<div class="spot_season">季節
		</div>
		<div class="spot_prefecture_address">ポット名/場所
		</div>
		<div class="spot_description">説明
		</div>
		<div class="spot_average_star">評価
	  	</div>
	</div>
	<!-- テーブルの中身 -->
	<div class="admin_spots">
		<% @spots.each do |spot| %>
			<div class="admin_spot_item">
				<div class="spot_image_btn">
					<div>
			        	<%= link_to image_tag(spot.images.url,class: "admin_spot_image"), spot_path(spot.id)%>
					</div>
					<div class="edit_destroy">
						<%= render 'spots/edit', spot: spot %>
						<%=link_to "削除", spot_path(spot.id),method: :delete,class: "btn btn-default btn-sm", data:{ confirm: "本当に<strong>#{spot.spot_name}</strong>を削除してよろしいですか？",cancel: "やめる",commit: "削除する"},title: "削除の確認" %>
					</div>
				</div>
				<div class="spot_season center_item">
					<%= spot.season %>
				</div>
				<div class="spot_prefecture_address">
					<div class="spot_prefecture">
						<%= spot.spot_name %>
					</div>
					<div class="spot_spot_address">
						<%= spot.spot_address %>
					</div>
				</div>
				<div class="spot_description">
					<%= spot.description %>
				</div>
				<div class="spot_average_star center_item">
		            <% if spot.average_star.present? %>
		              <%= spot.average_star.round(1) %> / 5.0
		            <% end %>
	          	</div>
			</div>
		<% end %>
	</div>
</div>
<%= paginate @spots, class: "paginate",:param_name => 'spot_page' %>
<!-- 同一ページで複数のページャを適用させる為、param_nameでページャを指定している -->

app/views/spots/_new.html.erb
<div class="new_spot">
	<h2>スポットの追加</h2>
	<%= form_with model:@spot, local: true do |f| %>
		<!-- エラー文 -->
		<% if @spot.errors.any? %>
	        <div class="errors">
	        	<h5><%= @spot.errors.count %>件のエラーが発生しました。</h5>
		        <% @spot.errors.full_messages.each do |message| %>
		            <p><%= message %></p>
		        <% end %>
		    </div>
    	<% end %>
    	<!-- ここまでエラー文 -->
		<div class="form-group">
			<%= f.label :spot_name, "スポット名", class:"label-bold" %><br>
			<%= f.text_field :spot_name ,class:"form-control form-ucr"%><br>
		</div>
		<div class="season_prefecture">
			<div class="form_season form-group">
				<%= f.label :season, "季節", class:"label-bold" %><br>
			    <%= f.select :season, Spot.seasons.keys, { prompt: '選択してください' } %>
			</div>
			<div class="form-group">
				<%= f.label :prefecture, "地域", class:"label-bold" %><br>
				<%= f.select :prefecture, Spot.prefectures.keys, { prompt: '選択してください' } %>
			</div>
		</div>
		<div class="form_address form-group">
			<%= f.label :spot_address, "場所", class:"label-bold" %><br>
			<%= f.text_field :spot_address ,class:"form-control form-ucr"%>
		</div>
		<div class="form-group">
			<%= f.label :description, "内容", class:"label-bold" %><br>
			<%= f.text_area :description ,class:"form-control form-ucr" %>
		</div>
		<div class="form-group">
			<%= f.label :images, "画像", class:"label-bold" %><br>
			<%= f.file_field :images, multipart: true %>
		</div>
		<div class="form-group">
			<%= f.submit '新規追加' ,class: "form-control btn btn-primary"%>
		</div>
	<% end %>
</div>

app/views/spots/_new_comment.html.erb
<div class="modal fade" id="modal-option" tabindex="-1" role="dialog" aria-labelledby="myModalOptionLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h3 class="modal-title" id="myModalOptionLabel">レビュー投稿</h3>
        <button type="button" class="close" data-dismiss="modal" aria-label="閉じる"><span aria-hidden="true">&times;</span></button>
      </div>
      <div class="modal-body">
        <div class="comment_post">
          <%= form_for [@spot,@comment] do |comment| %>
            <%= comment.hidden_field :spot_id, value: @spot.id %>
            <div class="field" id="star">
                <%= comment.label :評価 %>
                <%= comment.hidden_field :star, id: :review_star %>
                ※５段階で評価をつけてください。
            </div>
            <%= comment.file_field :comment_image %>
            <label><%= comment.label :comment %></label><br>
            <%= comment.text_area :comment, :size => "50x5",placeholder: "４文字以上９０文字以内で投稿してください。" %><br>
            <%= comment.submit "レビューを投稿する", :class => "btn btn-primary form-control" %>
          <% end %>
          <script>
          $('#star').raty({
            size:36,
            starOff:  '<%= asset_path('/images/star-off.png') %>',
            starOn : '<%= asset_path('/images/star-on.png') %>',
            scoreName: 'comment[star]'
          });
          </script>
        </div>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">閉じる</button>
      </div>
    </div>
  </div>
</div>

app/views/spots/_top.html.erb
<div class="top-container">
	<!-- サイトのトップイメージ -->
	<div class="top_image">
		<div class="tp top_image1"></div>
		<div class="tp top_image2"></div>
		<div class="tp top_image3"></div>
		<div class="tp top_image4"></div>
	</div>
	<!-- サイトの説明部分 -->
	<div class="about_site">
		<div class="site_discription">
			<h3 class="site_discription_title">四季たびとは</h3>
			<P>関東の観光名所を四季ごとにご紹介するサイトです。<br>
			ご覧いただく時期に合わせて見所をご紹介致します。<br>
			右上のメニューより、ご覧になりたい季節をお選びください。<br>
			会員登録して頂くと、レビューの投稿やお気に入り登録、<br>またユーザーのフォロー機能等がご使用いただけます。<br>
			会員登録は一切料金は発生致しません。<br>
		    登録される方は右上のメニュー一覧よりご登録ください。</P>
		</div>
	</div>
	<div class="recommendation_title">
		<h2>四季たびおすすめスポット</h2>
	</div>
	<div class="recommendation">
		<div class="recommendation_image">
			<%= image_tag @spot1.images.url, class: "recommendation_spot_image"%>
		</div>
		<div class="recommendation_content">
			<h4 class="spot_title"><%= @spot1.spot_name %></h4>
			<div class="spot_address">
				<h5><%= @spot1.spot_address %></h5>
			</div>
			<div class="recommend_text">
				<P><%= @spot1.description %></P>
			</div>
			<%= link_to "もっと見る", spot_path(@spot1.id),class: 'btn btn-default recommend_link'%>
		</div>
	</div>
	<div class="recommendation">
		<div class="recommendation_content">
			<h4 class="spot_title"><%= @spot2.spot_name %></h4>
			<div class="spot_address">
				<h5><%= @spot2.spot_address %></h5>
			</div>
			<div class="recommend_text">
				<P><%= @spot2.description %></P>
			</div>
			<%= link_to "もっと見る", spot_path(@spot2.id),class: 'btn btn-default recommend_link'%>
		</div>
		<div class="recommendation_image">
			<%= image_tag @spot2.images.url, class: "recommendation_spot_image"%>
		</div>
	</div>
	<%= render 'spots/footer' %>
</div>

app/views/spots/show.html.erb
<%= render 'spots/header' %>
<div class="show">
    <div class="show_top">
      <div class="show_top_left">
        <%= image_tag @spot.images.url, class: "spot_image"%>
      </div>
      <div class="show_top_right">
        <h3><%= @spot.spot_name %></h3>
      </div>
    </div>

    <div class="show_bottom">
      <div class="show_bottom_left">
        <div class="review">
          <h3 class="show_title">レビュー一覧</h3>
                  <% if @comment.errors.any? %>
            <div class="errors">
                <h5><%= @comment.errors.count %>件のエラーが発生しました。</h5>
                <% @comment.errors.full_messages.each do |message| %>
                    <p><%= message %></p>
                <% end %>
            </div>
        <% end %>
          <div class="score">
            <% if @spot.average_star.present? %>
              　<h4>このスポットの評価：<%= @spot.average_star.round(1) %> / 5.0</h4>
            <% end %>
          </div>
          <% if user_signed_in? %>
            <div class="new_comments">
              <button type="button" data-toggle="modal" data-backdrop="true" data-target="#modal-option" class="btn btn-default">レビューを投稿する</button>
            </div>
          <% end %>
        </div>
        <%= render 'spots/new_comment' %>
        <!-- コメント一覧表示 -->
        <div class="comment_list">
          <% @comments.each do |comment| %>
            <div class="comment_content">
              <%= image_tag comment.comment_image.url, class: "comment_image"%>
              <!-- 評価された星を表示する記述 -->
              <div class="rated_edit">
                <div class="rated" data-score="<%= comment.star %>"></div>
                <% if user_signed_in? && (current_user.id == comment.user_id || current_user.admin?) %>
                <!-- 投稿したユーザーと、管理者だけが投稿を削除できる -->
                  <%= render 'spots/edit_comment', comment: comment %>
                  <%=link_to "削除", spot_comment_path(comment.spot_id,comment.id),method: :delete,class: "btn btn-default btn-sm", data:{ confirm: "本当に削除してよろしいですか？",cancel: "やめる",commit: "削除する"},title: "削除の確認" %>
                <% end %>
              </div>
              <div class="comment_comment">
                <%= comment.comment %><br>
              </div>
              <div class="spot_comment_username">
                <div><%=link_to comment.user.nickname,user_path(comment.user.id) %></div>
                <div><%= comment.created_at.strftime("%Y-%m-%d") %></div>
              </div>
            </div>
          <% end %>
        </div>
      </div>

        <div class="show_bottom_right">
          <div class="spot_recommend">
            <h3 class="show_title">見どころ</h3>
            <div class="show_spot_description">
               <%= @spot.description %>
            </div>
            <div class="map_btn">
               <%= render 'spots/googlemap' %>
            </div>
          </div>
          <% if user_signed_in? %>
            <div class="post_favorite">
              <h3 class="show_title">気に入ったら</h3>
              <div class="show_spot_description">
                このスポットを気に入ったら、"お気に入り"に登録しましょう。<br>
                お気に入りに登録して頂くと、マイページのお気に入り一覧から<br>登録したスポットを確認することが出来ます。
              </div>
              <div class="favorite-btn">
                <% if @spot.favorited_by?(current_user) %>
                  <%= link_to "お気に入りから外す",spot_favorites_path(@spot),method: :delete,class: "btn btn-default" %>
                <% else %>
                  <%=link_to "お気に入りに追加する",spot_favorites_path(@spot),method: :post,class: "btn btn-default" %>
                <% end %>
              </div>
             </div>
           <% end %>
        </div>
    </div>
</div>

<!-- 評価された星を表示する記述 -->
<script>
  $('.rated').raty({
    path: '/images/',
    readOnly: true,
    score: function() {
      return $(this).attr('data-score');
    }
  });
</script>

app/views/spots/top.html.erb
<%= render 'spots/header' %>
<%= render 'spots/top' %>