config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  # post 'spots#create'
  get 'seasons/spring'
  get 'seasons/summer'
  get 'seasons/autumn'
  get 'seasons/winter'
  root 'spots#top'
  get '/', to: 'spots#top'
  # get '/spots/new', to: 'spots#new'
  # post '/spots', to: 'spots#create'
  resources :users,except:[:edit,:new,:create] do
    resource :relations,only:[:create,:destroy]
    get :follows, on: :member
    get :followers, on: :member
  end
  resources :relationships,only: [:create, :destroy]
  resources :spots,except:[:new] do
      resources :comments,only:[:create,:destroy,:edit,:update]
      resource :favorites,only:[:create,:destroy]
      resources :went_spots,only:[:create,:destroy]
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  	devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

		has_many :favorites,dependent: :destroy
		has_many :comments,dependent: :destroy
		has_many :went_spots,dependent: :destroy
		mount_uploader :user_image, UserImageUploader
    has_many :favorite_spots, through: :favorites, source: :spot
    #validates :introduciton,presence: true,length: {maximum:65}
    validates :nickname,presence: true,uniqueness: true,length: {minimum:2,maximum:8}
    validates :postal, format: {with: /\A[0-9]{3}-[0-9]{4}\z/}


  # ====================自分がフォローしているユーザーとの関連 ===================================
  #フォローする側のUserから見て、フォローされる側のUserを(中間テーブルを介して)集める。なので親はfollowing_id(フォローする側)
  has_many :active_relations, class_name: "Relation", foreign_key: :following_id
  # 中間テーブルを介して「follower」モデルのUser(フォローされた側)を集めることを「followings」と定義
  has_many :followings, through: :active_relations, source: :follower
  # ========================================================================================

  # ====================自分がフォローされるユーザーとの関連 ===================================
  #フォローされる側のUserから見て、フォローしてくる側のUserを(中間テーブルを介して)集める。なので親はfollower_id(フォローされる側)
  has_many :passive_relations, class_name: "Relation", foreign_key: :follower_id
  # 中間テーブルを介して「following」モデルのUser(フォローする側)を集めることを「followers」と定義
  has_many :followers, through: :passive_relations, source: :following
  # =======================================================================================
  def followed_by?(user)
    # 今自分(引数のuser)がフォローしようとしているユーザー(レシーバー)がフォローされているユーザー(つまりpassive)の中から、引数に渡されたユーザー(自分)がいるかどうかを調べる
    passive_relations.find_by(following_id: user.id).present?
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :admin_validate!, only: [:index]
  before_action :correct_user, only: [:show]
  before_action :create_user, only: [:update]

  def index
    # @spots = Spot.page(params[:spot_page]).per(6)
    @search = Spot.ransack(params[:q])
    @search_user = User.ransack(params[:q])
    @spots = @search.result.page(params[:spot_page]).per(6)
    @users = @search_user.result.page(params[:user_page]).per(8)
    @spot = Spot.new
  end

  def show
    @user = User.find(params[:id])
    @user_followers = @user.followers
    @user_followings = @user.followings
    @comments = @user.comments.page(params[:page])
    @favorites = current_user.favorite_spots.order(id: "desc")
  end
  def follows
    user = User.find(params[:id])
  end

  def followers
    user = User.find(params[:id])
    @user_followers = user.followers
  end

  def update
    @user = User.find(params[:id])
    @user_followers = @user.followers
    @user_followings = @user.followings
    @comments = @user.comments.page(params[:page])
    @favorites = current_user.favorite_spots.order(id: "desc")
    if @user.update(user_params)
      flash[:success] = "ユーザー情報を編集しました。"
      sign_in(@user, bypass: true) if current_user.id == @user.id
      #　パスワードを編集すると、deviseの特性上自動的にログアウトしてしまうので、それを防ぐ為の記述。
      redirect_to user_path(@user.id)
    else
      flash[:alert] = "ユーザー情報の編集に失敗しました。"
      render "show"
    end
  end

  def destroy
    user = User.find(params[:id])
    user.destroy
    redirect_to users_path
  end

  private
  def user_params
    params.require(:user).permit(:lastname,:firstname,:lastname_kana,:firstname_kana,:nickname,:postal,:address,:user_image,:email,:password,:password_confirmation,:user_image,:introduction)
  end
  def admin_validate!
    if user_signed_in? && current_user.admin?
    else
      redirect_to root_path
    end
  end
  def correct_user
    if user_signed_in?
    else
      redirect_to root_path
    end
  end
  def create_user
    user = User.find(params[:id])
    if user_signed_in? && current_user = user
    else
      redirect_to root_path
    end
  end

end

app/helpers/users_helper.rb
module UsersHelper

end

app/views/users/_followers.html.erb
<% @user_followers.each do |user| %>
　　<div class="follow_user">
	  <div class="follow_user_left">
	  <%= link_to image_tag(user.user_image.url,class: "follow_image"), user_path(user.id) %>
	  </div>
	  <div class="follow_user_right">
		    <div class="follow_user_nickname">
		    	<%= user.nickname %>
		    </div>
		    <div class="follow_user_introduction">
		    	<p><%= user.introduction %></p>
		    </div>
	  </div>
	</div>
<% end %>

app/views/users/_follows.html.erb
<% @user_followings.each do |user| %>
	<div class="follow_user">
	  <div class="follow_user_left">
	  <%= link_to image_tag(user.user_image.url,class: "follow_image"), user_path(user.id) %>
	  </div>
	  <div class="follow_user_right">
	    <div class="follow_user_nickname">
	    	<%= user.nickname %>
		    <% if current_user != user %>
		        <% if user.followed_by?(current_user) %>
		            <%=link_to "フォロー解除", user_relations_path(user.id), method: :delete,class: "btn btn-default btn-xs follow_btn" %>
		        <% else %>
		            <%=link_to "フォローする", user_relations_path(user.id), method: :post,class: "btn btn-default btn-xs" %>
		        <% end %>
		    <% end %>
	    </div>
	    <div class="follow_user_introduction">
	    	<p><%= user.introduction %></p>
	    </div>
	  </div>
	</div>
<% end %>

app/views/users/_index.html.erb
<div class="admin_spot_table">
	<div class="admin_spot_item_title">
		<div class="admin_user_image">イメージ
		</div>
		<div class="admin_user_name">名前
		</div>
		<div class="admin_user_nickname">ニックネーム
		</div>
		<div class="admin_user_address">住所
		</div>
		<div class="admin_user_email">メール
	  	</div>
	    <div class="admin_user_introduction">紹介文
		</div>
		<div class="admin_user_created_at">入会日
	  	</div>
	</div>

	<div class="admin_spots">
		<% @users.each do |user| %>
			<div class="admin_user_item">
				<div class="admin_user_image">
					<div class="admin_user_image_photo">
						<%= link_to image_tag(user.user_image.url,class: "admin_user_photo"),user_path(user.id)%>
					</div>
					<div class="edit_destroy">
						<button type="button" data-toggle="modal" data-backdrop="true" data-target="#modal<%=user.id%>-option" class="btn btn-default btn-sm user_edit">編集</button>
						<%= render 'users/user_edit',user: user%>
						<%=link_to "削除", user_path(user.id),method: :delete,class: "btn btn-default btn-sm", data:{ confirm: "本当に<strong>#{user.nickname}</strong>を削除してよろしいですか？",cancel: "やめる",commit: "削除する"},title: "削除の確認" %>
					</div>
				</div>
				<div class="admin_user_name">
					<div class="user_lastname_firstname">
						<%= user.lastname %> <%= user.firstname %>
					</div>
					<div class="admin_user_namekana">
						<%= user.lastname_kana %> <%= user.firstname_kana %>
					</div>
				</div>
				<div class="admin_user_nickname">
					<%= user.nickname %>
				</div>
				<div class="admin_user_address">
					<div class="admin_address_postal">
						<%= user.postal %>
					</div>
					<div class="admin_address_address">
						<%= user.address %>
					</div>
				</div>
				<div class="admin_user_email">
					<%= user.email %>
			  	</div>
			  	<div class="admin_user_introduction">
			  		<%= user.introduction %>
			  	</div>
			  	<div class="admin_user_created_at">
			  		<%= user.created_at.strftime("%Y-%m-%d") %>
			  	</div>
			</div>
		<% end %>
	</div>
</div>
<%= paginate @users, class: "paginate",:param_name => 'user_page' %>

app/views/users/_registration.html.erb
<button type="button" data-toggle="modal" data-backdrop="true" data-target="#modal4-option" class="btn btn-default">ログインする</button>

<div class="modal fade" id="modal4-option" tabindex="-1" role="dialog" aria-labelledby="myModalOptionLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="myModalOptionLabel">コメント投稿</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="閉じる"><span aria-hidden="true">&times;</span></button>
      </div>
      <div class="modal-body">
        <h2>Sign up</h2>

        <%= form_for(resource, as: resource_name, url: registration_path(resource_name)) do |f| %>
          <%= render "devise/shared/error_messages", resource: resource %>

          <div class="field">
            <span><p>※</p></span><%= f.label :lastname %><br />
            <%= f.text_field :lastname, autofocus: true, autocomplete: "lastname" %>
          </div>

          <div class="field">
            <%= f.label :firstname %><br />
            <%= f.text_field :firstname, autofocus: true, autocomplete: "firstname" %>
          </div>

          <div class="field">
            <%= f.label :lastname_kana %><br />
            <%= f.text_field :lastname_kana, autofocus: true, autocomplete: "lastname_kana" %>
          </div>

          <div class="field">
            <%= f.label :firstname_kana %><br />
            <%= f.text_field :firstname_kana, autofocus: true, autocomplete: "firstname_kana" %>
          </div>

          <div class="field">
            <%= f.label :nickname %><br />
            <%= f.text_field :nickname, autofocus: true, autocomplete: "nickname" %>
          </div>

          <div class="field">
            <%= f.label :postal %><br />
            <%= f.text_field :postal, autofocus: true, autocomplete: "postal" %>
          </div>

          <div class="field">
            <%= f.label :address %><br />
            <%= f.text_field :address, autofocus: true, autocomplete: "address" %>
          </div>

          <div class="field">
            <%= f.label :introduction %><br />
            <%= f.text_area :introduction, autofocus: true, autocomplete: "introduction" %>
          </div>

          <div class="field">
            <%= f.label :email %><br />
            <%= f.email_field :email, autofocus: true, autocomplete: "email" %>
          </div>

          <div class="field">
            <%= f.label :password %>
            <% if @minimum_password_length %>
            <em>(<%= @minimum_password_length %> characters minimum)</em>
            <% end %><br />
            <%= f.password_field :password, autocomplete: "new-password" %>
          </div>

          <div class="field">
            <%= f.label :password_confirmation %><br />
            <%= f.password_field :password_confirmation, autocomplete: "new-password" %>
          </div>

          <div class="actions">
            <%= f.submit "Sign up" %>
          </div>
        <% end %>
        <%= render "devise/shared/links" %>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">閉じる</button>
      </div>
    </div>
  </div>
</div>

app/views/users/_show.html.erb
  <div class="comment_list">
    <% @comments.each do |comment| %>
      <div class="comment_content ">
        <div class="comment_spot">
          <p><%= comment.spot.spot_name %></p>
        </div>
        <%= link_to (image_tag comment.comment_image.url, class: "comment_image"),spot_path(comment.spot_id)%>
        <!-- 評価された星を表示する記述 -->
        <div class="rated" data-score="<%= comment.star %>"></div>
        <!-- 評価された星を表示する記述 -->
        <script>
          $('.rated').raty({
            path: '/images/',
            readOnly: true,
            score: function() {
              return $(this).attr('data-score');
            }
          });
        </script>
        <div class="comment_comment">
          <%= comment.comment %><br>
        </div>
        <div class="comment_username">
          <div><%=link_to comment.user.nickname,user_path(comment.user.id) %></div>
          <div><%= comment.created_at.strftime("%Y-%m-%d") %></div>
        </div>
      </div>
    <% end %>
  </div>

app/views/users/_user_comments.html.erb
<div class="user_comments" id='shops'>
    <%= render partial: "show", collections:  "@comments" %>
</div>
<%= paginate @comments %>
<!-- <div class="page-load-status">
  <div class="infinit-scroll-request">
    <%#= image_tag '25.gif'%>
    <%= paginate @comments %>
  </div>
  <p class="infinite-scroll-last">last</p>
  <p class="infinite-scroll-error">error</p>
</div> -->
  <!-- 評価された星を表示する記述 -->
<script>
  $('.rated').raty({
    path: '/images/',
    readOnly: true,
    score: function() {
      return $(this).attr('data-score');
    }
  });
</script>

app/views/users/_user_edit.html.erb
<div class="modal fade" id="modal<%=user.id%>-option" tabindex="-1" role="dialog" aria-labelledby="myModalOptionLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="myModalOptionLabel">ユーザー編集</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="閉じる"><span aria-hidden="true">&times;</span></button>
      </div>

      <div class="modal-body">
        <span class="need">※は必須項目です。</span>
        <div class="edit_user_form">
          <%= form_for(user) do |f|%>
            <div class="registration_name">
              <div class="field">
                <span class="need">※</span><%= f.label :名字 %><br />
                <%= f.text_field :lastname, autofocus: true, autocomplete: "lastname" %>
              </div>

              <div class="field">
                <span class="need">※</span><%= f.label :名前 %><br />
                <%= f.text_field :firstname, autofocus: true, autocomplete: "firstname" %>
              </div>
            </div>
            <div class="registration_namekana">
              <div class="field">
                <span class="need">※</span><%= f.label :みょうじ %><br />
                <%= f.text_field :lastname_kana, autofocus: true, autocomplete: "lastname_kana" %>
              </div>

              <div class="field">
                <span class="need">※</span><%= f.label :なまえ %><br />
                <%= f.text_field :firstname_kana, autofocus: true, autocomplete: "firstname_kana" %>
              </div>
            </div>

            <div class="field">
              <span class="need">※</span><%= f.label :ニックネーム %><br />
              <%= f.text_field :nickname, autofocus: true, autocomplete: "nickname" ,class:"form-control"%>
            </div>
            <div class="form_address_introduction">
              <div class="address">
                <div class="field">
                  <span class="need">※</span><%= f.label :郵便番号 %><br />
                  <%= f.text_field :postal, autofocus: true, autocomplete: "postal" %>
                </div>

                <div class="field">
                  <span class="need">※</span><%= f.label :住所 %><br />
                  <%= f.text_area :address, autofocus: true, autocomplete: "address",:size => "20x2" %>
                </div>
              </div>
              <div class="field">
                <%= f.label :紹介文 %><br />
                <%= f.text_area :introduction, autofocus: true, autocomplete: "introduction",:size => "25x5" %>
              </div>
            </div>

            <div class="field">
              <span class="need">※</span><%= f.label :メール %><br />
              <%= f.email_field :email, autofocus: true, autocomplete: "email",class:"form-control" %>
            </div>

            <div class="field">
              <span class="need">※</span><%= f.label :パスワード %>
              <% if @minimum_password_length %>
              <em>(<%= @minimum_password_length %> characters minimum)</em>
              <% end %><br />
              <%= f.password_field :password, autocomplete: "new-password",class:"form-control" %>
            </div>

            <div class="field">
              <span class="need">※</span><%= f.label :"パスワード(確認用)" %><br />
              <%= f.password_field :password_confirmation, autocomplete: "new-password",class:"form-control" %>
            </div>

                    <div class="user_image">
                      <%= f.label :user_image, "ユーザー画像", class:"label-bold" %><br />
                      <%= f.file_field :user_image, multipart: true %>
                    </div>
            <div class="submit_btn actions">
              <%= f.submit "登録する",class:"btn btn-primary form-control" %>
            </div>
          <% end %>
        </div>

        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-dismiss="modal">閉じる</button>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/users/_user_favorite.html.erb
<div class="user_favorite">
	<div class="favorite_spot">
		<% @favorites.each do |spot| %>
	        <div class="favorite">
	        	<div class="favorite_top">
	        		<p><%= spot.spot_name %></p>
	          		<%= link_to image_tag(spot.images.url, class: "favorite_spot_image"),spot_path(spot.id)%>
	          	</div>
	          	<div class="favorite_center">
		          平均評価：
		          <div class="score2">
		            <% if spot.average_star.present? %>
		              　<%= spot.average_star.round(1) %> / 5.0
		            <% end %>
		          </div>
		        </div>
	            <div class="favorite_bottom">
	          	  <% if spot.favorited_by?(current_user) %>
	                 <%= link_to "お気に入りから外す",spot_favorites_path(spot),method: :delete,class: "btn btn-default" %>
	              <% end %>
	            </div>
	        </div>
		<% end %>
	</div>
</div>
<script>
  $('.rated').raty({
    path: '/images/',
    readOnly: true,
    score: function() {
      return $(this).attr('data-score');
    }
  });
</script>

app/views/users/index.html.erb
<%= render 'spots/header' %>

<div class="mypage_container ">
    <div class="mypage_left">
        <%= render 'spots/new' %>
    </div>
    <div class="mypage_right">
        <!-- タブ・メニュー -->
        <ul class="nav nav-tabs">
            <li class="active"><a href="#sampleContentC" data-toggle="tab">スポット一覧</a></li>
            <li><a href="#sampleContentD" data-toggle="tab">ユーザー一覧</a></li>
        </ul>

        <!-- タブ内容 -->
        <div class="tab-content">
            <div class="tab-pane active" id="sampleContentC">
                <div class="spot_search">
                    <%= search_form_for @search, url: users_path do |f| %>
                        <div class="form-group">
                            <%= f.text_field :spot_name_cont,:size=>"40",placeholder: "スポット名で検索" %>
                            <%=f.submit "検索する",class: "btn btn-primary btn-sm" %>
                        </div>
                    <% end %>
                </div>
                <%= render 'spots/index' %>
            </div>
            <div class="tab-pane" id="sampleContentD">
                <div class="spot_search">
                    <%= search_form_for @search_user, url: users_path do |f| %>
                        <div class="form-group">
                            <%= f.text_field :lastname_cont,:size=>"40",placeholder: "ユーザー名で検索" %>
                            <%=f.submit "検索する",class: "btn btn-primary btn-sm" %>
                        </div>
                    <% end %>
                </div>
                <%= render 'users/index' %>
            </div>
        </div>
    </div>
</div>

app/views/users/show.html.erb
<%= render 'spots/header' %>
<div class="mypage_container ">
    <div class="mypage_left">
        <!-- エラー文 -->
        <% if @user.errors.any? %>
            <div class="errors">
                <h5><%= @user.errors.count %>件のエラーが発生しました。</h5>
                <% @user.errors.full_messages.each do |message| %>
                    <p><%= message %></p>
                <% end %>
            </div>
        <% end %>
        <!-- ここまでエラー文 -->
        <div class="user_profile">
            <%= image_tag @user.user_image.url,class: "profile_image"%>
            <%= @user.nickname %>
            <div class="follow_edit">
                <% if current_user != @user %>
                    <% if @user.followed_by?(current_user) %>
                        <p><%=link_to "フォローを解除する", user_relations_path(@user.id), method: :delete,class: "btn btn-default" %></p>
                    <% else %>
                        <p><%=link_to "このユーザーをフォローする", user_relations_path(@user.id), method: :post ,class: "btn btn-default"%></p>
                    <% end %>
                <% else %>
                    <button type="button" data-toggle="modal" data-backdrop="true" data-target="#modal<%= @user.id %>-option" class="btn btn-default user_edit">ユーザー情報を編集する</button>
                    <%= render 'users/user_edit',user: @user %>
                <% end %>
            </div>
        </div>
        <div class="mypage_discription">
            <div class="discription_title"><h4>マイページについて</h4></div>
            <div class="discription_subtitle">お気に入り</div>
            <div class="discription_content">今までに登録した<br>お気に入りした一覧が見れます。</div>
            <div class="discription_subtitle">投稿履歴</div>
            <div class="discription_content">コメントを投稿した<br>履歴の一覧が見れます。</div>
            <div class="discription_subtitle">フォロー</div>
            <div class="discription_content">あなたがフォローしている<br>ユーザーの一覧が見れます。</div>
            <div class="discription_subtitle">フォロワー</div>
            <div class="discription_content">あなたがフォローされている<br>ユーザーの一覧が見れます。</div>
        </div>
    </div>
    <div class="mypage_right">
        <!-- タブ・メニュー -->
        <ul class="nav nav-tabs">
            <li class="active"><a href="#sampleContentB" data-toggle="tab">投稿履歴</a></li>
            <li><a href="#sampleContentC" data-toggle="tab">フォロー(<%= @user_followings.count %>)</a></li>
            <li><a href="#sampleContentD" data-toggle="tab">フォロワー(<%= @user_followers.count %>)</a></li>
            <% if @user == current_user %>

                <li><a href="#sampleContentA" data-toggle="tab">お気に入り</a></li>
            <% end %>
        </ul>

        <!-- タブ内容 -->
        <div class="tab-content">
            <div class="tab-pane active" id="sampleContentB">
                <%= render 'users/user_comments' %>
            </div>
            <div class="tab-pane" id="sampleContentC">
                <div class="following">
                    <%= render 'users/follows' %>
                </div>
            </div>
            <div class="tab-pane" id="sampleContentD">
                <div class="following">
                    <%= render 'users/followers' %>
                </div>
            </div>
            <% if @user == current_user %>
            <div class="tab-pane" id="sampleContentA">
                <%= render 'users/user_favorite' %>
            </div>
            <% end %>
        </div>
    </div>
</div>